// Project data for the portfolio "My Latest Work" section.
// categories drive the filter chips: "Blockchain" | "Full-Stack" | "Solana" | "EVM" | "Sui"
// github: repo URL (omit/null to hide the GitHub button, e.g. private repos)
// demo:   live URL (omit/null to hide the Live Demo button)
// image:  real screenshot in /public (omit to render a generated gradient thumbnail)
// accent: hex used for the gradient thumbnail + tag glow, gives each card a distinct look

export const mywork_data = [
  {
    w_no: 1,
    w_name: "Predex Prediction Market",
    desc: "AI-powered on-chain prediction market on Solana with a custom AMM for trading outcome shares. Built with Rust/Anchor and a Next.js frontend.",
    tags: ["Solana", "Rust", "Anchor", "AMM", "AI", "Next.js"],
    categories: ["Blockchain", "Solana", "Full-Stack"],
    accent: "#9945ff",
    featured: true,
    demo: "https://predex-prediction-market.vercel.app",
    github: null, // private repo, live demo only
    alt: "Predex prediction market dApp on Solana",
  },
  {
    w_no: 2,
    w_name: "NFT Marketplace",
    desc: "Full-stack NFT marketplace where users mint, list, buy and sell NFTs. Solidity smart contracts with IPFS metadata storage and a Next.js dApp.",
    tags: ["Solidity", "Next.js", "IPFS", "Ethers.js"],
    categories: ["Blockchain", "EVM", "Full-Stack"],
    accent: "#3a86ff",
    github:
      "https://github.com/DaniTechdev/WEB3-NFT-Marketplace-solidity-and-NextJs-FullStack-",
    demo: null,
    alt: "Web3 NFT marketplace dApp",
  },
  {
    w_no: 3,
    w_name: "Company Staff Management",
    desc: "On-chain role-based staff management dApp. Enforces permissions and records staff actions transparently on the blockchain via Solidity.",
    tags: ["Solidity", "Next.js", "On-chain RBAC"],
    categories: ["Blockchain", "EVM", "Full-Stack"],
    accent: "#06b6d4",
    image: "/company-management-blockchain.png",
    github:
      "https://github.com/DaniTechdev/Company-Staff-role-management-OnChain-blockchain-solidity-dapp-",
    demo: null,
    alt: "Blockchain company staff management dApp",
  },
  {
    w_no: 4,
    w_name: "Crowdfunding Platform",
    desc: "Decentralized crowdfunding where backers fund campaigns through trustless smart contracts that release funds based on on-chain rules.",
    tags: ["Solidity", "Smart Contracts", "Web3"],
    categories: ["Blockchain", "EVM"],
    accent: "#f59e0b",
    github:
      "https://github.com/DaniTechdev/CrowdFunding-SmartContract-Project-Solididty-",
    demo: null,
    alt: "Blockchain crowdfunding smart contract project",
  },
  {
    w_no: 5,
    w_name: "Token ICO Marketplace",
    desc: "ERC-20 token ICO and marketplace dApp. Launch, buy and manage tokens during a crowdsale with a Next.js interface.",
    tags: ["Solidity", "ERC-20", "Next.js"],
    categories: ["Blockchain", "EVM"],
    accent: "#10b981",
    github:
      "https://github.com/DaniTechdev/CRYTOToken-ICO-Marketplace-solidity--nextjs-",
    demo: null,
    alt: "Crypto token ICO marketplace dApp",
  },
  {
    w_no: 6,
    w_name: "Supply Chain Management",
    desc: "Blockchain supply-chain tracker that records each product's journey immutably, giving end-to-end provenance and transparency.",
    tags: ["Solidity", "JavaScript", "Next.js"],
    categories: ["Blockchain", "EVM", "Full-Stack"],
    accent: "#8b5cf6",
    github:
      "https://github.com/DaniTechdev/Supply-Chain-Management-solidity-javascript-nextjs",
    demo: null,
    alt: "Blockchain supply chain management dApp",
  },
  {
    w_no: 7,
    w_name: "Staking dApp with ICO",
    desc: "DeFi staking platform with an integrated ICO. Users stake tokens to earn rewards through audited Solidity staking contracts.",
    tags: ["Solidity", "DeFi", "Staking"],
    categories: ["Blockchain", "EVM"],
    accent: "#ec4899",
    github: "https://github.com/DaniTechdev/Staking-Dapp-With-ICO-SOLIDITY-",
    demo: null,
    alt: "DeFi staking dApp with ICO",
  },
  {
    w_no: 8,
    w_name: "Decentralized Voting System",
    desc: "Tamper-proof voting dApp where votes are cast and tallied on-chain, guaranteeing a transparent and verifiable election.",
    tags: ["Solidity", "JavaScript", "Web3"],
    categories: ["Blockchain", "EVM"],
    accent: "#ef4444",
    github:
      "https://github.com/DaniTechdev/decentralised-voting-system-solidity-",
    demo: null,
    alt: "Decentralized blockchain voting system",
  },
  {
    w_no: 9,
    w_name: "EtherScan Clone",
    desc: "Block explorer that reads live Ethereum chain data. Search transactions, blocks and wallet balances using Ethers.js.",
    tags: ["Ethers.js", "Next.js", "Web3"],
    categories: ["Blockchain", "EVM", "Full-Stack"],
    accent: "#0ea5e9",
    github: "https://github.com/DaniTechdev/etherscan-clone",
    demo: null,
    alt: "EtherScan block explorer clone",
  },
  {
    w_no: 10,
    w_name: "Sui Token dApp",
    desc: "Token functionality dApp on the Sui blockchain written in Move. Mint, transfer and manage tokens with a TypeScript frontend.",
    tags: ["Sui", "Move", "TypeScript"],
    categories: ["Blockchain", "Sui"],
    accent: "#4da2ff",
    github: "https://github.com/DaniTechdev/Sui-Token-functionionalities-dapp",
    demo: null,
    alt: "Sui Move token dApp",
  },
  {
    w_no: 11,
    w_name: "Full-Stack E-Commerce (MERN)",
    desc: "Complete MERN e-commerce store with product catalog, cart, auth and order management. Built with a React frontend, Node/Express API and MongoDB.",
    tags: ["React", "Node.js", "Express", "MongoDB"],
    categories: ["Full-Stack"],
    accent: "#22c55e",
    github: "https://github.com/DaniTechdev/Full-Stack-Ecommerce-app-MERN-",
    demo: null,
    alt: "Full-stack MERN e-commerce application",
  },
  {
    w_no: 12,
    w_name: "AI Image Generator",
    desc: "MERN-stack app that turns text prompts into AI-generated images and lets users share them to a community feed.",
    tags: ["MERN", "OpenAI", "React"],
    categories: ["Full-Stack"],
    accent: "#a855f7",
    github: "https://github.com/DaniTechdev/Ai-Image--generator-MERN-Stack",
    demo: null,
    alt: "AI image generator MERN app",
  },
  {
    w_no: 13,
    w_name: "Solana ICO dApp",
    desc: "Token sale dApp on Solana. Investors connect a wallet and buy tokens during a crowdsale backed by an on-chain program.",
    tags: ["Solana", "Web3.js", "JavaScript"],
    categories: ["Blockchain", "Solana"],
    accent: "#14f195",
    github: "https://github.com/DaniTechdev/Solana_ICO_dapp",
    demo: null,
    alt: "Solana token ICO dApp",
  },
];
